# Define the image that will be used for the job
image: maven:3.9.5-openjdk-21

# Define the stages of the pipeline
stages:
  - build
  - test

# Define the jobs
build:
  stage: build
  script:
    - mvn clean package -DskipTests

test:
  stage: test
  script:
    - mvn test

# Optional: Define other stages or jobs (e.g., deploy, deploy_to_production, etc.)
