server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:h2:file:./src/main/resources/data/testdb1
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
          format-sql: true
          database: h2

flyway:
  baselineOnMigrate: true